
<!-- Generated by ai2html v0.100.0 - 2024-08-18 18:32 -->
<!-- ai file: map.ai -->
<style lang="scss">
	#g-map-box ,
	#g-map-box .g-artboard {
		margin:0 auto;
	}
	#g-map-box p {
		margin:0;
	}
	#g-map-box .g-aiAbs {
		position:absolute;
	}
	#g-map-box .g-aiImg {
		position:absolute;
		top:0;
		display:block;
		width:100% !important;
		height: 100%;
		background-size: contain;
		background-repeat: no-repeat;
	}
	#g-map-box .g-aiPointText p { white-space: nowrap; }
	#g-map-2667 {
		position:relative;
		overflow:hidden;
	}
	#g-map-2667 p {
		font-family:Arial, sans-serif;
		font-weight:700;
		line-height:75px;
		height:auto;
		opacity:1;
		letter-spacing:0em;
		font-size:63px;
		text-align:left;
		color:rgb(255,255,255);
		text-transform:none;
		padding-bottom:0;
		padding-top:0;
		mix-blend-mode:normal;
		font-style:normal;
		position:static;
	}
	#g-map-2667 .g-pstyle0 {
		height:75px;
	}
	#g-map-1300 {
		position:relative;
		overflow:hidden;
	}
	#g-map-1300 p {
		font-family:Arial, sans-serif;
		font-weight:700;
		line-height:41px;
		height:auto;
		opacity:1;
		letter-spacing:0em;
		font-size:35px;
		text-align:left;
		color:rgb(255,255,255);
		text-transform:none;
		padding-bottom:0;
		padding-top:0;
		mix-blend-mode:normal;
		font-style:normal;
		position:static;
	}
	#g-map-1300 .g-pstyle0 {
		height:41px;
	}
	#g-map-900 {
		position:relative;
		overflow:hidden;
	}
	#g-map-900 p {
		font-family:Arial, sans-serif;
		font-weight:700;
		line-height:26px;
		height:auto;
		opacity:1;
		letter-spacing:0em;
		font-size:22px;
		text-align:left;
		color:rgb(255,255,255);
		text-transform:none;
		padding-bottom:0;
		padding-top:0;
		mix-blend-mode:normal;
		font-style:normal;
		position:static;
	}
	#g-map-900 .g-pstyle0 {
		height:26px;
	}

	/* Custom CSS */


</style>

<div id="g-map-box" bind:clientWidth={width}>

	<!-- Artboard: 2667 -->
{#if width && (width >= 2667)}	<div id="g-map-2667" class="g-artboard" style="">
<div style="padding: 0 0 56.243% 0;"></div>
		<div id="g-map-2667-img" class="g-aiImg" alt="" style="background-image: url({map2667});"></div>		<div id="g-ai0-1" class="g-icons g-aiAbs g-aiPointText" style="top:24.3824%;margin-top:-44.7px;left:66.261%;width:57px;">
			<p class="g-pstyle0">6</p>
		</div>
		<div id="g-ai0-2" class="g-icons g-aiAbs g-aiPointText" style="top:24.7824%;margin-top:-44.7px;left:46.7671%;width:57px;">
			<p class="g-pstyle0">4</p>
		</div>
		<div id="g-ai0-3" class="g-icons g-aiAbs g-aiPointText" style="top:29.7824%;margin-top:-44.7px;left:34.5989%;width:57px;">
			<p class="g-pstyle0">1</p>
		</div>
		<div id="g-ai0-4" class="g-icons g-aiAbs g-aiPointText" style="top:40.7824%;margin-top:-44.7px;left:34.2479%;width:57px;">
			<p class="g-pstyle0">2</p>
		</div>
		<div id="g-ai0-5" class="g-icons g-aiAbs g-aiPointText" style="top:47.5824%;margin-top:-44.7px;left:30.3504%;width:57px;">
			<p class="g-pstyle0">3</p>
		</div>
		<div id="g-ai0-6" class="g-icons g-aiAbs g-aiPointText" style="top:47.5824%;margin-top:-44.7px;left:49.2397%;width:57px;">
			<p class="g-pstyle0">5</p>
		</div>
		<div id="g-ai0-7" class="g-icons g-aiAbs g-aiPointText" style="top:67.6491%;margin-top:-44.7px;left:67.8757%;width:57px;">
			<p class="g-pstyle0">7</p>
		</div>
		<div id="g-ai0-8" class="g-icons g-aiAbs g-aiPointText" style="top:75.7824%;margin-top:-44.7px;left:53.451%;width:57px;">
			<p class="g-pstyle0">8</p>
		</div>
	</div>
{/if}
	<!-- Artboard: 1300 -->
{#if width && ( width >= 1300 && width <2667)}	<div id="g-map-1300" class="g-artboard" style="">
<div style="padding: 0 0 71.0595% 0;"></div>
		<div id="g-map-1300-img" class="g-aiImg" alt="" style="background-image: url({map1300});"></div>		<div id="g-ai1-1" class="g-icons g-aiAbs g-aiPointText" style="top:25.7956%;margin-top:-24.3px;left:76.6037%;width:41px;">
			<p class="g-pstyle0">6</p>
		</div>
		<div id="g-ai1-2" class="g-icons g-aiAbs g-aiPointText" style="top:26.1204%;margin-top:-24.3px;left:54.6191%;width:41px;">
			<p class="g-pstyle0">4</p>
		</div>
		<div id="g-ai1-3" class="g-icons g-aiAbs g-aiPointText" style="top:30.5587%;margin-top:-24.3px;left:40.8962%;width:41px;">
			<p class="g-pstyle0">1</p>
		</div>
		<div id="g-ai1-4" class="g-icons g-aiAbs g-aiPointText" style="top:40.4096%;margin-top:-24.3px;left:40.5004%;width:41px;">
			<p class="g-pstyle0">2</p>
		</div>
		<div id="g-ai1-5" class="g-icons g-aiAbs g-aiPointText" style="top:46.4717%;margin-top:-24.3px;left:36.105%;width:41px;">
			<p class="g-pstyle0">3</p>
		</div>
		<div id="g-ai1-6" class="g-icons g-aiAbs g-aiPointText" style="top:46.4717%;margin-top:-24.3px;left:57.4075%;width:41px;">
			<p class="g-pstyle0">5</p>
		</div>
		<div id="g-ai1-7" class="g-icons g-aiAbs g-aiPointText" style="top:66.7147%;margin-top:-24.3px;left:77.9837%;width:41px;">
			<p class="g-pstyle0">7</p>
		</div>
		<div id="g-ai1-8" class="g-icons g-aiAbs g-aiPointText" style="top:73.7511%;margin-top:-24.3px;left:61.9021%;width:41px;">
			<p class="g-pstyle0">8</p>
		</div>
	</div>
{/if}
	<!-- Artboard: 900 -->
{#if width && ( width >= 0 && width <1300)}	<div id="g-map-900" class="g-artboard" style="">
<div style="padding: 0 0 63.8168% 0;"></div>
		<div id="g-map-900-img" class="g-aiImg" alt="" style="background-image: url({map900});"></div>		<div id="g-ai2-1" class="g-icons g-aiAbs g-aiPointText" style="top:27.9354%;margin-top:-15.4px;left:72.0027%;width:34px;">
			<p class="g-pstyle0">6</p>
		</div>
		<div id="g-ai2-2" class="g-icons g-aiAbs g-aiPointText" style="top:28.2836%;margin-top:-15.4px;left:51.9482%;width:34px;">
			<p class="g-pstyle0">4</p>
		</div>
		<div id="g-ai2-3" class="g-icons g-aiAbs g-aiPointText" style="top:32.8104%;margin-top:-15.4px;left:39.4301%;width:34px;">
			<p class="g-pstyle0">1</p>
		</div>
		<div id="g-ai2-4" class="g-icons g-aiAbs g-aiPointText" style="top:42.7347%;margin-top:-15.4px;left:39.0691%;width:34px;">
			<p class="g-pstyle0">2</p>
		</div>
		<div id="g-ai2-5" class="g-icons g-aiAbs g-aiPointText" style="top:49.0026%;margin-top:-15.4px;left:35.0596%;width:34px;">
			<p class="g-pstyle0">3</p>
		</div>
		<div id="g-ai2-6" class="g-icons g-aiAbs g-aiPointText" style="top:49.0026%;margin-top:-15.4px;left:54.4919%;width:34px;">
			<p class="g-pstyle0">5</p>
		</div>
		<div id="g-ai2-7" class="g-icons g-aiAbs g-aiPointText" style="top:67.11%;margin-top:-15.4px;left:73.6637%;width:34px;">
			<p class="g-pstyle0">7</p>
		</div>
		<div id="g-ai2-8" class="g-icons g-aiAbs g-aiPointText" style="top:74.4226%;margin-top:-15.4px;left:58.8243%;width:34px;">
			<p class="g-pstyle0">8</p>
		</div>
	</div>
{/if}
</div>

<script>
	export let assetsPath = './';
	let width = null;
import { onMount } from 'svelte';
export let onAiMounted = () => {};
onMount(() => {
  onAiMounted();
});

import map900 from './map-900.jpg'
import map1300 from './map-1300.jpg'
import map2667 from './map-2667.jpg'

</script>
<!-- End ai2html - 2024-08-18 18:32 -->
