
<!-- Generated by ai2html v0.100.0 - 2024-10-14 13:42 -->
<!-- ai file: sherp42_map.ai -->
<style lang="scss">
	#g-sherp42_map-box ,
	#g-sherp42_map-box .g-artboard {
		margin:0 auto;
	}
	#g-sherp42_map-box p {
		margin:0;
	}
	#g-sherp42_map-box .g-aiAbs {
		position:absolute;
	}
	#g-sherp42_map-box .g-aiImg {
		position:absolute;
		top:0;
		display:block;
		width:100% !important;
		height: 100%;
		background-size: contain;
		background-repeat: no-repeat;
	}
	#g-sherp42_map-box .g-aiPointText p { white-space: nowrap; }
	#g-sherp42_map-MAP_BOUNDS {
		position:relative;
		overflow:hidden;
	}

	/* Custom CSS */


</style>

<div id="g-sherp42_map-box" bind:clientWidth={width}>

	<!-- Artboard: MAP_BOUNDS -->
{#if width && (width >= 0)}	<div id="g-sherp42_map-MAP_BOUNDS" class="g-artboard" style="">
<div style="padding: 0 0 56.243% 0;"></div>
		<div id="g-sherp42_map-MAP_BOUNDS-img" class="g-aiImg" alt="" style="background-image: url({MAP_BOUNDS});"></div>	</div>
{/if}
</div>

<script>
	export let assetsPath = './';
	let width = null;
import { onMount } from 'svelte';
export let onAiMounted = () => {};
onMount(() => {
  onAiMounted();
});

import MAP_BOUNDS from './sherp42_map-MAP_BOUNDS.png'

</script>
<!-- End ai2html - 2024-10-14 13:42 -->
